### ISSUE TITLE
Add SES to hapi mailer.

### ISSUE THREAD

**Issue by rajeev37** [gergoerdosi/hapi-mailer#18]
How do I add SES credentials to hapi mailer so that I check all mails from aws.

**Comment by gergoerdosi** [comment]
The `transport` options accepts any nodemailer transport, so you can use nodemailer-ses-transport (https://github.com/andris9/nodemailer-ses-transport). Something like this should work:

```js
var sesTransport = require('nodemailer-ses-transport');

var options = {
    transport: sesTransport({
        accessKeyId: "AWSACCESSKEY",
        secretAccessKey: "AWS/Secret/key",
        rateLimit: 5 // do not send more than 5 messages in a second
    })
}
```
